"""Generates ``examples/synthetic_winter_stress.csv`` — a deterministic 6-day
synthetic day-profile file for ``simulate --input`` demos. Not ISO-NE data; no
committed data fixture exists anywhere else in the repo.

Run with::

    uv run python examples/make_synthetic_winter_stress.py [output_path]

Days 1-3 are mild (flat load, ample wind); days 4-6 are a cold snap with identical
daily energy totals reached through different hourly shapes. The tie is enforced by
construction rather than typed by hand: each cold day's hour-23 load is the
remainder needed to reach ``COLD_DAY_TOTAL_MWH``, so reshaping hours 0-22 later
cannot silently break it. At the default ``--severity-percentile 0.90`` /
``--min-stress-window-days 2``, this makes all three cold days clear the threshold
as one 3-day stress window — the flagship demo command depends on that tie holding
exactly, so every invariant below is checked before anything is written.
"""

from __future__ import annotations

import sys
from datetime import date, timedelta

from owr.config import DEFAULT_CONFIG
from owr.models import DayProfile
from owr.stress_finder import find_stress_windows

START_DATE = date(2026, 1, 6)

# --- mild days (1-3): flat load, ample wind ---------------------------------
# One flat MW value per mild day (7,500-8,500 MW range), whole numbers.
MILD_DAY_LOADS_MW = (7500.0, 8000.0, 8500.0)
# Flat wind level, every hour of every mild day (1,500-3,000 MW range). Strictly
# positive so --lead-days can distinguish charging over 1 vs 3 lead days.
MILD_WIND_MW = 2000.0

# --- cold days (4-6): evening-peak stress, low wind --------------------------
COLD_FLAT_MW = 9000.0
COLD_PEAK_MW = 12000.0
COLD_SHOULDER_MW = 10000.0
# Flat wind level, every hour of every cold day (300-600 MW range).
COLD_WIND_MW = 400.0
# Shared daily total (MWh) all three cold days must hit exactly, so the default
# --severity-percentile 0.90 threshold selects all three as one 3-day window.
COLD_DAY_TOTAL_MWH = 216000.0

DEFAULT_OUTPUT_PATH = "examples/synthetic_winter_stress.csv"

BANNER_LINES = (
    "# Synthetic day-profile input for the simulator CLI. NOT ISO-NE data.",
    "# Generated by examples/make_synthetic_winter_stress.py -- do not hand-edit.",
)


def _mild_day(i: int) -> DayProfile:
    load = (MILD_DAY_LOADS_MW[i],) * 24
    wind = (MILD_WIND_MW,) * 24
    return DayProfile(date=START_DATE + timedelta(days=i), hourly_load_mw=load, hourly_wind_mw=wind)


def _cold_shape(peak_hour: int, shoulder_hour: int | None = None) -> tuple[float, ...]:
    """23 hourly values (hours 0-22); hour 23 is computed separately as the
    balancing remainder against COLD_DAY_TOTAL_MWH."""
    hours = [COLD_FLAT_MW] * 23
    hours[peak_hour] = COLD_PEAK_MW
    if shoulder_hour is not None:
        hours[shoulder_hour] = COLD_SHOULDER_MW
    return tuple(hours)


def _cold_day(offset: int, shape_23: tuple[float, ...]) -> DayProfile:
    if len(shape_23) != 23:
        raise ValueError("cold-day shape must supply exactly 23 hours (0-22)")
    hour23 = COLD_DAY_TOTAL_MWH - sum(shape_23)
    load = (*shape_23, hour23)
    wind = (COLD_WIND_MW,) * 24
    return DayProfile(
        date=START_DATE + timedelta(days=3 + offset), hourly_load_mw=load, hourly_wind_mw=wind
    )


def build_days() -> list[DayProfile]:
    mild = [_mild_day(i) for i in range(3)]
    cold = [
        _cold_day(0, _cold_shape(peak_hour=18)),
        _cold_day(1, _cold_shape(peak_hour=19)),
        _cold_day(2, _cold_shape(peak_hour=18, shoulder_hour=7)),
    ]
    return mild + cold


def _check_invariants(days: list[DayProfile]) -> None:
    assert len(days) == 6, f"expected 6 days, got {len(days)}"
    for d in days:
        assert len(d.hourly_load_mw) == 24, f"{d.date}: expected 24 hourly rows"
        for v in d.hourly_load_mw:
            assert float(v).is_integer(), f"{d.date}: non-integer load {v}"

    for d in days[3:]:
        closing = d.hourly_load_mw[23]
        peak = max(d.hourly_load_mw)
        assert closing > 0, f"{d.date}: computed closing hour is not positive ({closing})"
        assert closing <= peak, f"{d.date}: computed closing hour ({closing}) exceeds peak ({peak})"

    assert days[3].load_mwh == days[4].load_mwh == days[5].load_mwh, (
        "cold-day daily totals must be exactly tied"
    )

    mild_totals = [d.load_mwh for d in days[:3]]
    cold_totals = [d.load_mwh for d in days[3:]]
    assert min(cold_totals) > max(mild_totals), (
        "every cold-day total must strictly exceed every mild-day total"
    )

    for d in days[:3]:
        assert all(w > 0 for w in d.hourly_wind_mw), (
            f"{d.date}: mild day must have positive wind in every hour"
        )

    for prev_d, next_d in zip(days, days[1:], strict=False):
        assert next_d.date - prev_d.date == timedelta(days=1), "dates must be consecutive"
    assert len(days) == 6

    windows = find_stress_windows(
        days,
        DEFAULT_CONFIG.default_severity_percentile,
        DEFAULT_CONFIG.default_min_stress_window_days,
    )
    assert len(windows) == 1, f"expected exactly one stress window, got {len(windows)}"
    assert windows[0].days == 3, f"expected a 3-day window, got {windows[0].days}"
    assert windows[0].start == days[3].date
    assert windows[0].end == days[5].date


def render_csv(days: list[DayProfile]) -> str:
    lines = [*BANNER_LINES, "date,hour,load_mw,wind_mw"]
    for d in days:
        for h in range(24):
            lines.append(
                f"{d.date.isoformat()},{h},{d.hourly_load_mw[h]:.1f},{d.hourly_wind_mw[h]:.1f}"
            )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    output_path = argv[1] if len(argv) > 1 else DEFAULT_OUTPUT_PATH
    days = build_days()
    _check_invariants(days)
    content = render_csv(days)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
